# Generated by Django 3.2.3 on 2021-07-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas_app', '0002_appointment_user_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user_task',
        ),
    ]
