# Generated by Django 3.2.3 on 2021-07-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas_app', '0003_remove_appointment_user_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='citas_app.user'),
            preserve_default=False,
        ),
    ]
